server:
  port: 8081

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: user-service
  cloud:
    config:
      enabled: false
    openfeign:
      circuitbreaker:
        enabled: true
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/trusta_market}
    username: ${DB_USERNAME:trusta_admin}
    password: ${DB_PASSWORD:trusta_admin_pw}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    show-sql: ${JPA_SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: ${JPA_FORMAT_SQL:true}
        dialect: ${JPA_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:http://localhost:9090/realms/trusta}

resilience4j:
  circuitbreaker:
    instances:
      wallet-service:
        baseConfig: default
    configs:
      default:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 3
        registerHealthIndicator: true

trusta:
  gateway:
    headers: ${TRUST_GATEWAY_HEADERS:true}
  keycloak:
    server-url: ${KEYCLOAK_SERVER_URL:http://localhost:9090}
    realm: ${KEYCLOAK_REALM:trusta}
    client-id: ${KEYCLOAK_CLIENT_ID:admin-cli}
    username: ${KEYCLOAK_USERNAME:admin}
    password: ${KEYCLOAK_PASSWORD:admin}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
    register-with-eureka: ${EUREKA_REGISTER:true}
    fetch-registry: ${EUREKA_FETCH:true}
  instance:
    prefer-ip-address: ${EUREKA_PREFER_IP_ADDRESS:true}
