--liquibase formatted sql

--changeset seungwon:1
CREATE TABLE IF NOT EXISTS p_users (
    user_id        UUID         NOT NULL,
    created_at     TIMESTAMPTZ,
    updated_at     TIMESTAMPTZ,
    deleted_at     TIMESTAMPTZ,
    created_by     UUID,
    deleted_by     UUID,
    updated_by     UUID,
    email          VARCHAR(100) NOT NULL,
    keycloak_id    VARCHAR(100) NOT NULL,
    membership     VARCHAR(20)  NOT NULL,
    name           VARCHAR(100) NOT NULL,
    role           VARCHAR(20)  NOT NULL,
    slack_id       VARCHAR(100),
    user_status    VARCHAR(20)  NOT NULL,
    version        INT          NOT NULL,
    CONSTRAINT pk_p_users              PRIMARY KEY (user_id),
    CONSTRAINT uk_p_users_keycloak_id  UNIQUE (keycloak_id),
    CONSTRAINT uk_p_users_email        UNIQUE (email),
    CONSTRAINT uk_p_users_name         UNIQUE (name)
);

--changeset seungwon:2
CREATE TABLE IF NOT EXISTS p_accounts (
    account_id     UUID         NOT NULL,
    created_at     TIMESTAMPTZ,
    updated_at     TIMESTAMPTZ,
    deleted_at     TIMESTAMPTZ,
    created_by     UUID,
    deleted_by     UUID,
    updated_by     UUID,
    account_holder VARCHAR(50)  NOT NULL,
    account_number VARCHAR(100) NOT NULL,
    account_type   VARCHAR(20)  NOT NULL,
    approved_at    TIMESTAMP,
    approved_by    UUID,
    bank_code      VARCHAR(10)  NOT NULL,
    is_default     BOOLEAN      NOT NULL,
    is_verified    BOOLEAN      NOT NULL,
    user_id        UUID         NOT NULL,
    version        INT          NOT NULL,
    CONSTRAINT pk_p_accounts PRIMARY KEY (account_id)
);

--changeset seungwon:3
CREATE TABLE IF NOT EXISTS p_addresses (
    address_id      UUID         NOT NULL,
    created_at      TIMESTAMPTZ,
    updated_at      TIMESTAMPTZ,
    deleted_at      TIMESTAMPTZ,
    created_by      UUID,
    deleted_by      UUID,
    updated_by      UUID,
    address         VARCHAR(200) NOT NULL,
    address_detail  VARCHAR(100),
    is_default      BOOLEAN      NOT NULL,
    recipient_name  VARCHAR(50)  NOT NULL,
    recipient_phone VARCHAR(20)  NOT NULL,
    user_id         UUID         NOT NULL,
    version         INT          NOT NULL,
    zip_code        VARCHAR(10)  NOT NULL,
    CONSTRAINT pk_p_addresses PRIMARY KEY (address_id)
);

--changeset seungwon:4
CREATE TABLE IF NOT EXISTS p_trust_scores (
    trust_score_id UUID   NOT NULL,
    created_at     TIMESTAMPTZ,
    updated_at     TIMESTAMPTZ,
    score          BIGINT NOT NULL,
    user_id        UUID   NOT NULL,
    version        INT    NOT NULL,
    CONSTRAINT pk_p_trust_scores      PRIMARY KEY (trust_score_id),
    CONSTRAINT uk_p_trust_scores_user UNIQUE (user_id)
);

--changeset seungwon:5
CREATE TABLE IF NOT EXISTS p_reports (
    report_id        UUID         NOT NULL,
    created_at       TIMESTAMPTZ,
    reason           VARCHAR(200) NOT NULL,
    reported_user_id UUID         NOT NULL,
    reporter_user_id UUID         NOT NULL,
    reviewed_at      TIMESTAMP,
    reviewed_by      UUID,
    status           VARCHAR(20)  NOT NULL,
    version          INT          NOT NULL,
    CONSTRAINT pk_p_reports PRIMARY KEY (report_id)
);

--changeset seungwon:6
CREATE TABLE IF NOT EXISTS user_membership_history (
    membership_history_id UUID         NOT NULL,
    created_at            TIMESTAMPTZ,
    next_membership       VARCHAR(255) NOT NULL,
    prev_membership       VARCHAR(255) NOT NULL,
    reason                VARCHAR(200),
    user_id               UUID         NOT NULL,
    CONSTRAINT pk_user_membership_history PRIMARY KEY (membership_history_id)
);

--changeset seungwon:7
CREATE TABLE IF NOT EXISTS user_status_history (
    status_history_id UUID         NOT NULL,
    created_at        TIMESTAMPTZ,
    next_status       VARCHAR(255) NOT NULL,
    prev_status       VARCHAR(255) NOT NULL,
    reason            VARCHAR(200),
    user_id           UUID         NOT NULL,
    CONSTRAINT pk_user_status_history PRIMARY KEY (status_history_id)
);

--changeset seungwon:8
CREATE TABLE IF NOT EXISTS user_suspension (
    suspension_id   UUID         NOT NULL,
    created_at      TIMESTAMPTZ,
    expires_at      TIMESTAMP,
    reason          VARCHAR(200) NOT NULL,
    released_at     TIMESTAMP,
    released_by     UUID,
    released_reason VARCHAR(200),
    user_id         UUID         NOT NULL,
    CONSTRAINT pk_user_suspension PRIMARY KEY (suspension_id)
);

--changeset seungwon:9
CREATE TABLE IF NOT EXISTS wallet_creation_tasks (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at         TIMESTAMP,
    last_error_message VARCHAR(255),
    retry_count        INT,
    status             VARCHAR(255) NOT NULL,
    updated_at         TIMESTAMP,
    user_id            UUID         NOT NULL,
    CONSTRAINT pk_wallet_creation_tasks      PRIMARY KEY (id),
    CONSTRAINT uk_wallet_creation_tasks_user UNIQUE (user_id)
);
